name: Combpile Rust to WebAssembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
     - uses: mymindstorm/setup-emsdk@v13
     - name: Verify
       run: emcc -v
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests (TODO)
      run: echo cargo test --verbose
        
