name: Combile Rust to WebAssembly

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build Rust
    runs-on: ubuntu-latest
    steps:
    - uses: mymindstorm/setup-emsdk@v13
    - name: Verify
      run: emcc -v

    - name: Update Rust
      run: rustup update beta && rustup default beta
    - name: Verify Rust
      run: rustc --version

    - name: Add emscripten to rustc
      run: rustup target add  wasm32-unknown-emscripten
      
    - uses: actions/checkout@v3
    - name: Verify ls 
      run: ls -R 
    - name: Build
      run: cargo build --verbose --target wasm32-unknown-emscripten --release
      
    - name: Run tests (TODO)
      run: echo cargo test --verbose
        
